name: mpabot-tools

services:
  # MPAbot Tools apidoc (9093)
  mpabot-tools-web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=mpabot-tools-backend:9093
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 140:140
    depends_on:
      - mpabot-tools-backend
    networks:
      - subnet

  # MPAbot backend
  mpabot-tools-backend:
    container_name: mpabot-tools-backend
    image: mpabot-tools_backend
    build:
      context: application
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9093
      - MONGO_URI=mongodb://mpabot-tools-mongo:27017/mpabot-tools_db
    volumes:
      - ./application:/src
    depends_on:
      -  mpabot-tools-mongo
    networks:
      - mpabot-net
      - data-net
      - subnet

  # MPAbot Tools DB (50000)
  mpabot-tools-mongo:
    container_name: mpabot-tools-mongo
    image: mongo
    ports:
      - 50000:27017
    volumes:
      - mpabot-tools-data:/data/db
    networks:
      - subnet

networks:
  data-net:
    external:
      name: mpabot_data_controller_data-net
  mpabot-net:
    driver: bridge
  subnet:
    driver: bridge


volumes:
  mpabot-tools-data:
  kaggle-data:
